### ISSUE TITLE
Create About page

### ISSUE THREAD

**Issue by AndyFou** [OSWINDS/TweetFix#32]
- [x] add info for project 
- [x] add info for OSWINDS
- [x] add info for team
- [x] add contact for us
- [x] add project flow (?)

**Comment by AndyFou** [comment]
@syfantid add the paragraphs you wrote here as comments

**Comment by syfantid** [comment]
@AndyFou 

About the Project:

“FIX the FIXING: Proactive quelling of sports events manipulation” is an Erasmus+ Collaborative Partnership, which utilizes state-of-the-art scientific knowledge and methods, in order to understand match fixing in sports, develop an educational tool that provides updated information and resources about abstaining from match fixing, as well as educate stakeholders and end-users about the harms of match fixing and how to abstain. More details can be found on the <a href="http://fixthefixing.eu">project’s webpage</a>.

“TWEETFIX” is a project developed by OSWINDS Research Group as part of this collaborative partnership (A26, A27, A28 in WP5: Crowdsourced content retrieval and modelling). The goal is to crowdsource social media on the topic of match fixing. “TWEETFIX” performs social media mining regarding match fixing cases and related people on Twitter, Youtube and Google+, as well as data analytics and sentiment analysis techniques on the collected data, while it also enables the visualization of the results through an online platform.

**Comment by syfantid** [comment]
@AndyFou 

About us:
The <a href=” http://oswinds.csd.auth.gr/oswinds2015profiles/OSWINDS_profile.pdf”>OSWINDS</a> (Online Sources analytics on Web and INternet Distributed platformS) research group belongs to the <a href=” http://plase.csd.auth.gr/”>Programming Languages and Software Engineering Lab</a> of the <a href=” http://www.csd.auth.gr/en/”>Department of Informatics</a> at the <a href=” http://www.auth.gr/en”>Aristotle University of Thessaloniki</a>.

OSWINDS is an active research group engaged in research and development activities in the areas of ICT technologies and their implementations, with additional interest on multi-disciplinary synergies. The mission of OSWINDS is to enable research and innovation progress and development with cultivating a collaborative and knowledge sharing spirit with internal and International collaborations under common research work and projects. OSWINDS work aims at high quality research as well as at applied research and experimenting.

The team is involved in research and experimentation with a focus on topics of big data management, Web and social network mining and analytics, content delivery and management on the Web, as well as on sentiment analytics. OSWINDS expertise and targeting is primarily on the following areas:

<ul>
<li>Evolving big data analytics
<li>Social media analytics (usage and content summarization)
<li>Smart cities (IoT) and social networks data integration
<li>Cloud-based evolving data streams management 
<li>Societal and cultural innovation via ICT technologies 
</ul>

**Comment by AndyFou** [comment]
PREVIEW
![image](https://cloud.githubusercontent.com/assets/8682216/19223954/0d968950-8e84-11e6-9d16-07fc92a52bff.png)

**Comment by AndyFou** [comment]
Idea: add information about the developing team

Solution #1 (without info)
![image](https://cloud.githubusercontent.com/assets/8682216/19224230/5b5f00f8-8e8a-11e6-8052-fbec2277b593.png)

**Comment by AndyFou** [comment]
Solution #2 
![image](https://cloud.githubusercontent.com/assets/8682216/19224370/39fdde72-8e8d-11e6-8def-86225f708c8e.png)
